server:
  port: 801

eureka:
  client:
    #表示是否将自己注册进Eurekaserver默认为true。
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka, http://eureka7002.com:7002/eureka


feign:
  client:
    config:
      default:
        #指的是建立连接所用的时间，适用于网络状况正常的情况下,两端连接所用的时间
        connectTimeout: 5000
        #指的是建立连接后从服务器读取到可用资源所用的时间
        readTimeout: 5000
        loggerLevel: basic


logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.nocdy.springcloud.service.PaymentFeignService: debug
